name: Tests
on:
  push:
    branches:
      - dev
      - staging
      - main
    tags:
      - v*
  pull_request:

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
    - name: Pull dependencies
      uses: actions/checkout@v3
      with:
          repository: fetchoracle/usingFetch
          ref: dev
          token: ${{ github.token }}
          path: usingfetch
    - name: Pull repo
      uses: actions/checkout@v3
      with:
          path: autoPay
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: Install Node Dependencies
      working-directory: ./autoPay
      run: npm install
    - name: Run Tests
      working-directory: ./autoPay
      run: npx hardhat test
      env:
        CI: true
        # These are not needed for the tests but
        # hardhat fails to start when not present.
        NODE_URL_RINKEBY: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        NODE_URL_MAINNET: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        PRIVATE_KEY: "00000000000000000000000000000000000000000000000000"